<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuranSurahSeeder extends Seeder
{
    public function run()
    {
        // Kosongkan tabel dulu agar tidak duplikat
        DB::table('quran_surahs')->truncate();

        $surahs = [
            [1, 'Al-Fatihah', 'الفاتحة', 7],
            [2, 'Al-Baqarah', 'البقرة', 286],
            [3, 'Ali Imran', 'آل عمران', 200],
            [4, 'An-Nisa', 'النساء', 176],
            [5, 'Al-Maidah', 'المائدة', 120],
            [6, 'Al-Anam', 'الأنعام', 165],
            [7, 'Al-Araf', 'الأعراف', 206],
            [8, 'Al-Anfal', 'الأنفال', 75],
            [9, 'At-Taubah', 'التوبة', 129],
            [10, 'Yunus', 'يونس', 109],
            [11, 'Hud', 'هود', 123],
            [12, 'Yusuf', 'يوسف', 111],
            [13, 'Ar-Rad', 'الرعد', 43],
            [14, 'Ibrahim', 'إبراهيم', 52],
            [15, 'Al-Hijr', 'الحجر', 99],
            [16, 'An-Nahl', 'النحل', 128],
            [17, 'Al-Isra', 'الإسراء', 111],
            [18, 'Al-Kahfi', 'الكهف', 110],
            [19, 'Maryam', 'مريم', 98],
            [20, 'Thaha', 'طه', 135],
            [21, 'Al-Anbiya', 'الأنبياء', 112],
            [22, 'Al-Hajj', 'الحج', 78],
            [23, 'Al-Muminun', 'المؤمنون', 118],
            [24, 'An-Nur', 'النور', 64],
            [25, 'Al-Furqan', 'الفرقان', 77],
            [26, 'Asy-Syuara', 'الشعراء', 227],
            [27, 'An-Naml', 'النمل', 93],
            [28, 'Al-Qashash', 'القصص', 88],
            [29, 'Al-Ankabut', 'العنكبوت', 69],
            [30, 'Ar-Rum', 'الروم', 60],
            [31, 'Luqman', 'لقمان', 34],
            [32, 'As-Sajdah', 'السجدة', 30],
            [33, 'Al-Ahzab', 'الأحزاب', 73],
            [34, 'Saba', 'سبأ', 54],
            [35, 'Fathir', 'فاطر', 45],
            [36, 'Yasin', 'يس', 83],
            [37, 'Ash-Shaffat', 'الصافات', 182],
            [38, 'Shad', 'ص', 88],
            [39, 'Az-Zumar', 'الزمر', 75],
            [40, 'Ghafir', 'غافر', 85],
            [41, 'Fushshilat', 'فصلت', 54],
            [42, 'Asy-Syura', 'الشورى', 53],
            [43, 'Az-Zukhruf', 'الزخرف', 89],
            [44, 'Ad-Dukhan', 'الدخان', 59],
            [45, 'Al-Jatsiyah', 'الجاثية', 37],
            [46, 'Al-Ahqaf', 'الأحقاف', 35],
            [47, 'Muhammad', 'محمد', 38],
            [48, 'Al-Fath', 'الفتح', 29],
            [49, 'Al-Hujurat', 'الحجرات', 18],
            [50, 'Qaf', 'ق', 45],
            [51, 'Adz-Dzariyat', 'الذاريات', 60],
            [52, 'Ath-Thur', 'الطور', 49],
            [53, 'An-Najm', 'النجم', 62],
            [54, 'Al-Qamar', 'القمر', 55],
            [55, 'Ar-Rahman', 'الرحمن', 78],
            [56, 'Al-Waqiah', 'الواقعة', 96],
            [57, 'Al-Hadid', 'الحديد', 29],
            [58, 'Al-Mujadilah', 'المجادلة', 22],
            [59, 'Al-Hasyr', 'الحشر', 24],
            [60, 'Al-Mumtahanah', 'الممتحنة', 13],
            [61, 'Ash-Shaff', 'الصف', 14],
            [62, 'Al-Jumuah', 'الجمعة', 11],
            [63, 'Al-Munafiqun', 'المنافقون', 11],
            [64, 'At-Taghabun', 'التغابن', 18],
            [65, 'Ath-Thalaq', 'الطلاق', 12],
            [66, 'At-Tahrim', 'التحريم', 12],
            [67, 'Al-Mulk', 'الملك', 30],
            [68, 'Al-Qalam', 'القلم', 52],
            [69, 'Al-Haqqah', 'الحاقة', 52],
            [70, 'Al-Maarij', 'المعارج', 44],
            [71, 'Nuh', 'نوح', 28],
            [72, 'Al-Jinn', 'الجن', 28],
            [73, 'Al-Muzzammil', 'المزمل', 20],
            [74, 'Al-Muddatstsir', 'المدثر', 56],
            [75, 'Al-Qiyamah', 'القيامة', 40],
            [76, 'Al-Insan', 'الإنسان', 31],
            [77, 'Al-Mursalat', 'المرسلات', 50],
            [78, 'An-Naba', 'النبأ', 40],
            [79, 'An-Naziat', 'النازعات', 46],
            [80, 'Abasa', 'عبس', 42],
            [81, 'At-Takwir', 'التكوير', 29],
            [82, 'Al-Infithar', 'الإنفطار', 19],
            [83, 'Al-Muthaffifin', 'المطففين', 36],
            [84, 'Al-Insyiqaq', 'الإنشقاق', 25],
            [85, 'Al-Buruj', 'البروج', 22],
            [86, 'Ath-Thariq', 'الطارق', 17],
            [87, 'Al-Ala', 'الأعلى', 19],
            [88, 'Al-Ghasyiyah', 'الغاشية', 26],
            [89, 'Al-Fajr', 'الفجر', 30],
            [90, 'Al-Balad', 'البلد', 20],
            [91, 'Asy-Syams', 'الشمس', 15],
            [92, 'Al-Lail', 'الليل', 21],
            [93, 'Adh-Dhuha', 'الضحى', 11],
            [94, 'Al-Insyirah', 'الشرح', 8],
            [95, 'At-Tin', 'التين', 8],
            [96, 'Al-Alaq', 'العلق', 19],
            [97, 'Al-Qadr', 'القدر', 5],
            [98, 'Al-Bayyinah', 'البينة', 8],
            [99, 'Az-Zalzalah', 'الزلزلة', 8],
            [100, 'Al-Adiyat', 'العاديات', 11],
            [101, 'Al-Qariah', 'القارعة', 11],
            [102, 'At-Takatsur', 'التكاثر', 8],
            [103, 'Al-Ashr', 'العصر', 3],
            [104, 'Al-Humazah', 'الهمزة', 9],
            [105, 'Al-Fil', 'الفيل', 5],
            [106, 'Quraisy', 'قريش', 4],
            [107, 'Al-Maun', 'الماعون', 7],
            [108, 'Al-Kautsar', 'الكوثر', 3],
            [109, 'Al-Kafirun', 'الكافرون', 6],
            [110, 'An-Nashr', 'النصر', 3],
            [111, 'Al-Lahab', 'المسد', 5],
            [112, 'Al-Ikhlas', 'الإخلاص', 4],
            [113, 'Al-Falaq', 'الفلق', 5],
            [114, 'An-Nas', 'الناس', 6],
        ];

        $data = [];
        foreach ($surahs as $surah) {
            $data[] = [
                'id' => $surah[0],
                'name_latin' => $surah[1],
                'name_arabic' => $surah[2],
                'total_verses' => $surah[3],
                'created_at' => now(),
                'updated_at' => now(),
            ];
        }

        DB::table('quran_surahs')->insert($data);
    }
}